### ISSUE TITLE
Undefined Method Configure

### ISSUE THREAD

**Issue by Bontgoy** [solidusio-contrib/solidus_product_feed#50]
The README documents...
```
SolidusProductFeed.configure do |config|
  config.title = 'My Awesome Store'
  config.link = 'https://www.awesomestore.com'
  config.description = 'Find out about new products on https://www.awesomestore.com first!'
  config.language = 'en-us'
end
```

Attempting this results in...
```
/config/initializers/solidus_product_feed.rb:1:in `<top (required)>': undefined method `configure' for SolidusProductFeed:Module (NoMethodError)
```

Gem version: 
```
    solidus_product_feed (1.0.0)
      solidus_backend (>= 1.0, < 3)
```

The directory Im using is `config/initializers/solidus_product_feed.rb`

**Comment by aldesantis** [comment]
@Bontgoy you need to get the gem from GitHub rather than RubyGems, the latest release doesn't contain the `.configure` method.

Try the following:

```ruby
gem 'solidus_product_feed', github: 'solidusio-contrib/solidus_product_feed'
```

**Comment by Bontgoy** [comment]
@aldesantis thank you. I had to update `solidus_support` to fix some issues with dependancies but otherwise worked like a charm.
